import type { HarnessSnapshot } from "@/lib/types";

const now = "2026-07-28T00:00:00.000Z";
const weekAgo = "2026-07-21T00:00:00.000Z";
const monthAgo = "2026-06-28T00:00:00.000Z";

export const seedData: HarnessSnapshot = {
  members: [
    {
      id: "member_alex",
      name: "Alex Rivera",
      email: "alex@krakenlab.media",
      role: "admin",
      avatar: "/avatars/alex.png",
      createdAt: monthAgo,
    },
    {
      id: "member_jordan",
      name: "Jordan Kim",
      email: "jordan@krakenlab.media",
      role: "lead",
      createdAt: monthAgo,
    },
    {
      id: "member_sam",
      name: "Sam Patel",
      email: "sam@krakenlab.media",
      role: "dev",
      createdAt: monthAgo,
    },
    {
      id: "member_taylor",
      name: "Taylor Brooks",
      email: "taylor@krakenlab.media",
      role: "viewer",
      createdAt: weekAgo,
    },
  ],

  projects: [
    {
      id: "proj_harness",
      name: "KrakenLab Harness",
      slug: "krakenlab-harness",
      description:
        "Company operating system — projects, Hermes AI, costs, CRM, and Cursor agent delegation.",
      status: "active",
      goals: [
        "Ship MVP dashboard for team visibility",
        "Integrate Hermes with Groq for in-app assistant",
        "Wire Cursor agent delegation",
      ],
      startDate: "2026-05-01",
      targetDate: "2026-08-15",
      progress: 62,
      repoUrl: "https://github.com/krakenlab/harness",
      stack: ["Next.js", "Supabase", "Groq", "Tailwind", "trigger.dev"],
      createdAt: monthAgo,
      updatedAt: now,
    },
    {
      id: "proj_pulse",
      name: "Pulse Analytics",
      slug: "pulse-analytics",
      description:
        "Client-facing analytics dashboard with realtime Supabase feeds and Redis-backed aggregations.",
      status: "active",
      goals: [
        "Launch beta with 3 pilot clients",
        "Sub-200ms query p95 on heavy reports",
        "Stripe billing integration",
      ],
      startDate: "2026-04-10",
      targetDate: "2026-09-30",
      progress: 45,
      repoUrl: "https://github.com/krakenlab/pulse-analytics",
      stack: ["Next.js", "Supabase", "Redis", "Stripe", "Vercel"],
      createdAt: monthAgo,
      updatedAt: weekAgo,
    },
    {
      id: "proj_inkwell",
      name: "Inkwell CMS",
      slug: "inkwell-cms",
      description:
        "Headless CMS for media clients with AI-assisted content workflows via OpenRouter.",
      status: "planning",
      goals: [
        "Finalize content model schema",
        "Prototype AI drafting with Gemini",
        "Define migration path from legacy WordPress",
      ],
      startDate: "2026-07-01",
      targetDate: "2026-11-01",
      progress: 12,
      repoUrl: "https://github.com/krakenlab/inkwell-cms",
      stack: ["Next.js", "Supabase", "OpenRouter", "AI SDK", "Resend"],
      createdAt: weekAgo,
      updatedAt: weekAgo,
    },
  ],

  sprints: [
    {
      id: "sprint_harness_3",
      projectId: "proj_harness",
      name: "Sprint 3 — Hermes Core",
      goal: "Ship Hermes agent, tools, and offline demo mode.",
      startDate: "2026-07-14",
      endDate: "2026-07-28",
      status: "active",
      ticketIds: [
        "ticket_hermes_agent",
        "ticket_hermes_tools",
        "ticket_harness_ui",
        "ticket_cost_rollup",
      ],
    },
    {
      id: "sprint_pulse_2",
      projectId: "proj_pulse",
      name: "Sprint 2 — Redis Reports",
      goal: "Cache heavy aggregation queries and ship export feature.",
      startDate: "2026-07-07",
      endDate: "2026-07-21",
      status: "completed",
      ticketIds: ["ticket_redis_cache", "ticket_csv_export"],
    },
  ],

  tickets: [
    {
      id: "ticket_hermes_agent",
      projectId: "proj_harness",
      sprintId: "sprint_harness_3",
      title: "Implement Hermes agent with Groq",
      description:
        "Wire generateText with llama-3.3-70b-versatile, system prompt, and harness context.",
      status: "in_progress",
      priority: "critical",
      assigneeId: "member_sam",
      labels: ["ai", "backend"],
      createdAt: weekAgo,
      updatedAt: now,
      hermesNotes: "Offline fallback should use store snapshot for demos.",
    },
    {
      id: "ticket_hermes_tools",
      projectId: "proj_harness",
      sprintId: "sprint_harness_3",
      title: "Define Hermes tool schemas",
      description:
        "Zod schemas for projects, tickets, costs, CRM, agents, guidelines, and budgets.",
      status: "review",
      priority: "high",
      assigneeId: "member_sam",
      labels: ["ai", "types"],
      createdAt: weekAgo,
      updatedAt: now,
    },
    {
      id: "ticket_harness_ui",
      projectId: "proj_harness",
      sprintId: "sprint_harness_3",
      title: "Dashboard shell and navigation",
      description: "Layout, sidebar, and project overview cards.",
      status: "todo",
      priority: "medium",
      assigneeId: "member_jordan",
      labels: ["frontend", "ui"],
      createdAt: weekAgo,
      updatedAt: weekAgo,
    },
    {
      id: "ticket_cost_rollup",
      projectId: "proj_harness",
      sprintId: "sprint_harness_3",
      title: "Provider cost rollup widget",
      description: "Show budget vs actual across Vercel, Supabase, Groq, etc.",
      status: "todo",
      priority: "medium",
      assigneeId: "member_jordan",
      labels: ["frontend", "costs"],
      createdAt: weekAgo,
      updatedAt: weekAgo,
    },
    {
      id: "ticket_redis_cache",
      projectId: "proj_pulse",
      sprintId: "sprint_pulse_2",
      title: "Redis cache layer for report queries",
      description: "Cache aggregated metrics with 5-minute TTL.",
      status: "done",
      priority: "high",
      assigneeId: "member_sam",
      labels: ["backend", "performance"],
      createdAt: monthAgo,
      updatedAt: weekAgo,
    },
    {
      id: "ticket_csv_export",
      projectId: "proj_pulse",
      sprintId: "sprint_pulse_2",
      title: "CSV export for dashboard reports",
      description: "Allow clients to download filtered report data.",
      status: "done",
      priority: "medium",
      assigneeId: "member_sam",
      labels: ["feature"],
      createdAt: monthAgo,
      updatedAt: weekAgo,
    },
    {
      id: "ticket_inkwell_schema",
      projectId: "proj_inkwell",
      title: "Design Inkwell content model",
      description: "Articles, media assets, authors, and taxonomy tables.",
      status: "backlog",
      priority: "medium",
      assigneeId: "member_jordan",
      labels: ["planning", "database"],
      createdAt: weekAgo,
      updatedAt: weekAgo,
    },
    {
      id: "ticket_cursor_delegate",
      projectId: "proj_harness",
      title: "Cursor agent delegation API",
      description: "POST to Cursor API with local queue fallback.",
      status: "in_progress",
      priority: "high",
      assigneeId: "member_sam",
      labels: ["integrations"],
      createdAt: weekAgo,
      updatedAt: now,
    },
  ],

  activities: [
    {
      id: "act_001",
      projectId: "proj_harness",
      entityType: "ticket",
      entityId: "ticket_hermes_agent",
      action: "status_changed",
      summary: "Moved Hermes agent ticket to in_progress",
      actorId: "member_sam",
      createdAt: now,
    },
    {
      id: "act_002",
      projectId: "proj_pulse",
      entityType: "sprint",
      entityId: "sprint_pulse_2",
      action: "completed",
      summary: "Sprint 2 — Redis Reports marked completed",
      actorId: "member_jordan",
      createdAt: weekAgo,
    },
    {
      id: "act_003",
      projectId: "proj_harness",
      entityType: "project",
      entityId: "proj_harness",
      action: "progress_updated",
      summary: "Harness progress updated to 62%",
      actorId: "member_alex",
      createdAt: weekAgo,
    },
    {
      id: "act_004",
      entityType: "contact",
      entityId: "crm_nova",
      action: "note_added",
      summary: "Hermes insight added for Nova Media Group",
      actorId: "member_alex",
      createdAt: weekAgo,
    },
    {
      id: "act_005",
      projectId: "proj_inkwell",
      entityType: "project",
      entityId: "proj_inkwell",
      action: "created",
      summary: "Inkwell CMS project created",
      actorId: "member_jordan",
      createdAt: weekAgo,
    },
  ],

  costs: [
    {
      id: "cost_vercel",
      provider: "vercel",
      name: "Vercel Pro (team)",
      monthlyBudgetUsd: 200,
      actualSpendUsd: 142.5,
      notes: "Preview deployments driving usage",
      updatedAt: now,
    },
    {
      id: "cost_supabase",
      provider: "supabase",
      name: "Supabase Pro",
      monthlyBudgetUsd: 75,
      actualSpendUsd: 68.2,
      updatedAt: now,
    },
    {
      id: "cost_stripe",
      provider: "stripe",
      name: "Stripe (fees)",
      monthlyBudgetUsd: 50,
      actualSpendUsd: 31.4,
      updatedAt: now,
    },
    {
      id: "cost_openai",
      provider: "openai",
      name: "OpenAI API",
      monthlyBudgetUsd: 100,
      actualSpendUsd: 23.8,
      notes: "Legacy scripts only — migrating to Groq/OpenRouter",
      updatedAt: now,
    },
    {
      id: "cost_groq",
      provider: "groq",
      name: "Groq (Hermes)",
      monthlyBudgetUsd: 80,
      actualSpendUsd: 12.6,
      updatedAt: now,
    },
    {
      id: "cost_trigger",
      provider: "trigger",
      name: "trigger.dev",
      monthlyBudgetUsd: 60,
      actualSpendUsd: 45.0,
      updatedAt: now,
    },
    {
      id: "cost_resend",
      provider: "resend",
      name: "Resend",
      monthlyBudgetUsd: 30,
      actualSpendUsd: 8.5,
      updatedAt: now,
    },
    {
      id: "cost_gcp",
      provider: "gcp",
      name: "GCP (storage + compute)",
      monthlyBudgetUsd: 150,
      actualSpendUsd: 89.3,
      updatedAt: now,
    },
    {
      id: "cost_redis",
      provider: "redis",
      name: "Upstash Redis",
      monthlyBudgetUsd: 40,
      actualSpendUsd: 22.1,
      updatedAt: now,
    },
    {
      id: "cost_openrouter",
      provider: "openrouter",
      name: "OpenRouter",
      monthlyBudgetUsd: 120,
      actualSpendUsd: 34.7,
      notes: "Inkwell CMS prototyping",
      updatedAt: now,
    },
  ],

  stack: [
    {
      id: "stack_next",
      projectId: "proj_harness",
      name: "next",
      category: "framework",
      version: "16.2.12",
      critical: true,
      status: "healthy",
    },
    {
      id: "stack_supabase",
      projectId: "proj_harness",
      name: "@supabase/supabase-js",
      category: "database",
      version: "2.110.9",
      critical: true,
      status: "healthy",
    },
    {
      id: "stack_groq",
      projectId: "proj_harness",
      name: "@ai-sdk/groq",
      category: "ai",
      version: "4.0.14",
      critical: true,
      status: "healthy",
    },
    {
      id: "stack_ai",
      projectId: "proj_harness",
      name: "ai",
      category: "ai",
      version: "7.0.38",
      critical: true,
      status: "healthy",
    },
    {
      id: "stack_redis_pulse",
      projectId: "proj_pulse",
      name: "ioredis",
      category: "cache",
      version: "5.4.1",
      critical: true,
      status: "healthy",
    },
    {
      id: "stack_stripe_pulse",
      projectId: "proj_pulse",
      name: "stripe",
      category: "payments",
      version: "17.5.0",
      critical: true,
      status: "outdated",
      notes: "Upgrade to v18 planned",
    },
    {
      id: "stack_trigger",
      projectId: "proj_harness",
      name: "@trigger.dev/sdk",
      category: "background",
      version: "3.3.12",
      critical: false,
      status: "healthy",
    },
    {
      id: "stack_resend",
      projectId: "proj_inkwell",
      name: "resend",
      category: "email",
      version: "4.0.1",
      critical: false,
      status: "healthy",
    },
  ],

  agents: [
    {
      id: "agent_001",
      type: "feature",
      title: "Add cost rollup chart component",
      prompt:
        "Create a reusable CostRollupChart component showing provider budget vs spend with bar charts.",
      status: "completed",
      cursorAgentId: "bc_demo_001",
      prUrl: "https://github.com/krakenlab/harness/pull/12",
      repo: "https://github.com/krakenlab/harness",
      createdAt: weekAgo,
      updatedAt: weekAgo,
      resultSummary: "PR merged — chart component added with tests.",
    },
    {
      id: "agent_002",
      type: "bugfix",
      title: "Fix Redis connection pooling in Pulse",
      prompt:
        "Investigate connection leak in report cache service; add proper pool lifecycle.",
      status: "running",
      cursorAgentId: "bc_demo_002",
      repo: "https://github.com/krakenlab/pulse-analytics",
      createdAt: now,
      updatedAt: now,
    },
  ],

  contacts: [
    {
      id: "crm_nova",
      name: "Morgan Lee",
      email: "morgan@novamedia.com",
      company: "Nova Media Group",
      status: "active",
      ownerId: "member_alex",
      notes: "Long-term client; interested in Inkwell CMS beta.",
      hermesInsight:
        "High engagement — schedule Q3 roadmap review. Upsell opportunity for analytics add-on.",
      lastContactAt: weekAgo,
      createdAt: monthAgo,
    },
    {
      id: "crm_brightwave",
      name: "Casey Nguyen",
      email: "casey@brightwave.io",
      company: "Brightwave Studios",
      status: "lead",
      ownerId: "member_jordan",
      notes: "Inbound from conference; needs custom dashboard.",
      hermesInsight: "Warm lead — send Pulse demo and case study within 48h.",
      lastContactAt: weekAgo,
      createdAt: weekAgo,
    },
    {
      id: "crm_summit",
      name: "Riley Chen",
      email: "riley@summitpress.com",
      company: "Summit Press",
      status: "partner",
      ownerId: "member_alex",
      notes: "Referral partner for publishing clients.",
      lastContactAt: monthAgo,
      createdAt: monthAgo,
    },
  ],

  deals: [
    {
      id: "deal_nova_inkwell",
      contactId: "crm_nova",
      title: "Inkwell CMS Enterprise License",
      valueUsd: 48000,
      stage: "proposal",
      probability: 65,
      expectedClose: "2026-09-15",
      hermesInsight:
        "Strong fit — Nova's WordPress pain points align with Inkwell migration story.",
      createdAt: weekAgo,
    },
    {
      id: "deal_brightwave_pulse",
      contactId: "crm_brightwave",
      title: "Pulse Analytics — Studio Tier",
      valueUsd: 12000,
      stage: "discovery",
      probability: 35,
      expectedClose: "2026-10-01",
      hermesInsight: "Needs ROI calculator; emphasize Redis performance wins.",
      createdAt: weekAgo,
    },
  ],

  repos: [
    {
      id: "repo_harness",
      name: "krakenlab/harness",
      url: "https://github.com/krakenlab/harness",
      allowedActions: ["read", "write", "agents", "deploy", "secrets"],
      budgetUsdMonthly: 150,
      enabled: true,
    },
    {
      id: "repo_pulse",
      name: "krakenlab/pulse-analytics",
      url: "https://github.com/krakenlab/pulse-analytics",
      allowedActions: ["read", "write", "agents", "deploy"],
      budgetUsdMonthly: 100,
      enabled: true,
    },
  ],

  budgets: [
    {
      id: "budget_infra",
      category: "Infrastructure",
      monthlyLimitUsd: 500,
      spentUsd: 342.5,
      alertThresholdPct: 80,
    },
    {
      id: "budget_ai",
      category: "AI & LLM",
      monthlyLimitUsd: 300,
      spentUsd: 71.1,
      alertThresholdPct: 75,
    },
    {
      id: "budget_agents",
      category: "Cursor Agents",
      monthlyLimitUsd: 200,
      spentUsd: 48.0,
      alertThresholdPct: 85,
    },
  ],

  hermesMessages: [
    {
      id: "msg_001",
      channel: "in_app",
      role: "user",
      content: "What's the status of the Harness project?",
      contextType: "project",
      contextId: "proj_harness",
      createdAt: weekAgo,
    },
    {
      id: "msg_002",
      channel: "in_app",
      role: "assistant",
      content:
        "KrakenLab Harness is 62% complete and active. Sprint 3 (Hermes Core) is in progress with 4 tickets — the Hermes agent and tool schemas are the top priorities.",
      contextType: "project",
      contextId: "proj_harness",
      createdAt: weekAgo,
    },
    {
      id: "msg_003",
      channel: "in_app",
      role: "user",
      content: "How are we doing on cloud spend this month?",
      createdAt: weekAgo,
    },
    {
      id: "msg_004",
      channel: "in_app",
      role: "assistant",
      content:
        "Total provider spend is ~$478 against ~$905 budgeted. Vercel ($142.50) and GCP ($89.30) are the largest line items. AI spend is well under budget at $71.",
      createdAt: weekAgo,
    },
  ],
};
